version: "3.7"
services:
  db:
    image: postgres:14.6
    restart: always
    volumes:
      - db_data:/var/postgres/
    user: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5001:5432"
      # sudo service postgresql stop
  web:
    build: .
    env_file:
      - ./.env.development
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
    command: npm run dev
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data: 
    driver: local

  